import { StyleSheet } from "react-native";

export const colors = {
  primary: "#8DD54F",
  secondary: "#54932f",
  lime: "#c3eba0",
  lightgreen: "#f0f8eb",
  blue: "#A8F4FF",
  darkblue: "#158fd4",
  lightblue: "#f1f8fd",
  orange: "#FFB425",
  darkorange: "#FFB425",
  yellow: "#FFE662",
  lightorange: "#FFF0D3",
  violet: "#BF8FFD",
  lightviolet: "#d8bbfe",
  text: "#333333",
  white: "#ffffff",
  red: "#FA003F",
  lightred: "#fa84a2",
  lightgrey: "#CDCDCD"
};

export const spacing = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
};

export const textStyles = StyleSheet.create({
  default: {
    fontFamily: "ABeeZee",
    color: colors.text,
    fontSize: 16,
    lineHeight: 19,
  },
  mainTitle: {
    fontSize: 50,
    color: colors.white,
    fontFamily: "LuckiestGuy",
    marginBottom: 30,
    marginTop: 10,
    textAlign: "center",
    alignSelf: "center",
  },
  subtitle: {
    fontSize: 22,
    color: colors.white,
    fontFamily: "ABeeZee",
    marginBottom: 10,
    textAlign: "center",
    alignSelf: "center",
  },
  title: {
    fontFamily: "LuckiestGuy",
    color: colors.violet,
    fontSize: 32,
    marginBottom: 10,
    textAlign: "center",
  },
  label: {
    fontSize: 14,
    fontFamily: "ABeeZee",
    color: colors.darkblue,
    marginVertical: 10,
  },
  buttonText: {
    fontFamily: "ABeeZee",
    fontSize: 18,
    color: colors.text,
  },
  formButtonText: {
    fontFamily: "ABeeZee",
    fontSize: 18,
    color: colors.white,
  },
  buttonTextInner: {
    color: "#ffffff",
    fontFamily: "NunitoBold",
  },
});

export const layout = StyleSheet.create({
  screen: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 80,
    backgroundColor: colors.lightgreen,
  },
  mainContainer: {
    flex: 1,
    backgroundColor: colors.primary,
    justifyContent: "center",
    alignItems: "center",
    padding: 10,
  },
  container: {
    padding: 10,
    flex: 1,
    backgroundColor: colors.primary,
  },
  wrapper: {
    padding: 10,
    backgroundColor: colors.lightgreen,
  },
  navbarWrapper: {
    position: "absolute",
    bottom: 20,
    left: 20,
    right: 20,
    backgroundColor: "transparent",
  },
  innerContainer: {
    flex: 1,
    backgroundColor: colors.white,
    paddingHorizontal: 16,
    paddingVertical: 20,
  },
  formContainer: {
    backgroundColor: colors.lightgreen,
    borderColor: colors.darkblue,
    borderWidth: 3,
    borderRadius: 20,
    paddingHorizontal: 30,
    paddingVertical: 30,
    width: "100%",
    minHeight: 350,
  },
  notification: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: colors.lightgreen,
    borderColor: colors.darkblue,
    borderWidth: 2,
    borderRadius: 15,
    paddingHorizontal: 15,
    paddingVertical: 15,
    width: "100%",
    marginVertical: 5
  },
  shadowStyle: {
    shadowColor: "#000",
    shadowOffset: { width: 4, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 5,
  },
  button: {
    minWidth: 150,
    width: '100%',
    height: 60,
    backgroundColor: "#fff",
    borderRadius: 50,
    borderWidth: 3,
    borderColor: colors.darkblue,
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 15,
  },
  formButton: {
    width: '100%',
    height: 50,
    backgroundColor: colors.violet,
    borderRadius: 50,
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 15,
  },
  input: {
    height: 50,
    lineHeight: 30,
    borderColor: colors.darkblue,
    borderWidth: 2,
    borderRadius: 15,
    backgroundColor: colors.white,
    marginBottom: 10,
  },
  center: {
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
  },
  avatar: {
    width: 35,
    height: 35,
    borderWidth: 3,
    borderColor: colors.secondary,
    borderRadius: 100,
  },
  image: {
    width: 75,
    height: 75,
    marginRight: 10,
    borderWidth: 3,
    borderColor: colors.secondary,
    borderRadius: 15,
  },
  flagImage: {
    width: 35,
    height: 35,
    marginHorizontal: 5,
    borderWidth: 2,
    borderColor: colors.white,
    borderRadius: 35,
  },
  buttonInner: {
    width: 120,
    height: 50,
    borderRadius: 50,
    backgroundColor: colors.secondary,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
  },
  infoCard: {
    flexDirection: 'column',
    alignItems: 'center',
    padding: 10,
    borderRadius: 20,
    borderWidth: 3,
    borderColor: colors.darkblue,
    backgroundColor: '#f0f8eb',
    overflow: 'visible',
    marginVertical: 20,
    alignSelf: 'stretch',
  },
  cardWrapper: {
    backgroundColor: colors.lightgreen,
    borderColor: colors.secondary,
    borderWidth: 2,
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 30,
    marginVertical: 10,
    width: "100%",
  },
  langWrap: {
    flexDirection: "row",
    columnGap: 10,
    marginVertical: 5,
    flex: 1,
    alignItems: "center",
    borderWidth: 2,
    borderColor: "transparent",
    borderRadius: 50,
  },
  menuItem: {
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#ddd",
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: "center"
  },
  menuText: {
    fontSize: 16,
    fontWeight: "500",
  },
  settingsItem: {
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#ddd",
  },
  playButton: {
    backgroundColor: colors.orange,
    width: "100%",
    borderRadius: 50,
    height: 50,
    flexDirection: "row",
    columnGap: 15,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    alignSelf: "flex-end"
  },
  playButtonText: {
    fontSize: 18,
    fontWeight: 400,
    color: colors.white
  },
  deleteButton: {
    backgroundColor: colors.red,
    width: 100,
    height: 34,
    borderRadius: 12,
    alignSelf: "flex-end",
    margin: 5,
    alignItems: "center",
    justifyContent: "center",
    paddingBottom: 5
  }
});
